### ISSUE TITLE
ec performance of small blocksize is worse when including init time

### ISSUE THREAD

**Issue by egggHang** [intel/isa-l#100]
By using `erasure_code_perf`, the performance of small blocksize, like 1KB, is even worse than other larger size. This happens because it includes the initial operation (and other operations when decode) in the benchmark range.  So will it be better to move other funcs than `ec_encode_data`  out of the benchmark range?

**Comment by gbtucker** [comment]
@egggHang, it is true that the init is only necessary once for encode or decode before any number of blocks are encoded or recovered so it doesn't really belong inside the timed benchmark loop.  Similar for decode, the construction of the recovery matrix need only be performed once and doesn't belong in the timed loop.  I suggest we change to just time the ec_encode_data() function.  I can try to get this in for next release.

**Comment by gbtucker** [comment]
fixed by #104
