### ISSUE TITLE
Broken cross compile

### ISSUE THREAD

**Issue by caoli5288** [intel/isa-l#106]
```
$ ./configure --host=x86_64-w64-mingw32
...
checking for yasm... yes
checking for modern yasm... yes
checking for optional yasm AVX512 support... no
checking for nasm... yes
checking for modern nasm... yes
checking for optional nasm AVX512 support... yes
checking for additional nasm AVX512 support... no
configure: error: Mingw build requires Yasm 1.2.0 or later.
```

See #105

**Comment by gbtucker** [comment]
I've been working on this the past few days.  There are three issues really.  1) A modification to tools/test_extended.sh was keeping the mingw build from being run.  2) there was a symbol conflict in a newly added file that only builds with mingw and 3) the autoconf test for assembler had a fix-up for mingw in the wrong place after adding new arch tests.  I've pushed fixes for all three.  Can you retest on the latest tip?

**Comment by caoli5288** [comment]
It's seems ok now. :)

**Comment by gbtucker** [comment]
Thanks for the issue and testing.
