### ISSUE TITLE
gf_invert_matrix() modifies input matrix

### ISSUE THREAD

**Issue by Hi-Angel** [intel/isa-l#116]
[Purpose of `gf_invert_matrix()` function is to take an input matrix, calculate its inverse, and write into the output matrix](https://github.com/intel/isa-l/blob/f430953f0adb6c0b93a0f890ccbb66a1ec704985/include/erasure_code.h#L927). But I stumbled upon a confusing undocumented behavior: the function always modifies the input matrix.

I could write up a fix for it, but I'm not clear if it's a bug or is it just undocumented. Unfortunately, ISA-L functions in general often lack `const`s in arguments, so I can't draw any conclusion simply from the fact that the argument is not marked as such .

## Steps to reproduce *(in terms of terminal commands)*

```c++
$ cat test.cpp
#include <cstdio>
#include <isa-l.h>
#include <vector>

using u8vec = std::vector<uint8_t>;

void print_matrix(const u8vec& matrix, size_t n_rows, size_t n_cols) {
    for (size_t i_row = 0; i_row < n_rows; ++i_row) {
        for (size_t i_col = 0; i_col < n_cols; ++i_col)
            printf("%02x ", matrix[i_row * n_cols + i_col]);
        puts("");
    }
}

int main() {
    const size_t n_cols = 3, n_rows = 3;
    u8vec in_matrix = {1, 1, 1
                      ,1, 1, 1
                      ,1, 1, 1};
    u8vec out_matrix(in_matrix.size(), 0); // matrix with zeroes
    puts("'In matrix' before gf_invert_matrix:");
    print_matrix(in_matrix, n_rows, n_cols);

    gf_invert_matrix(in_matrix.data(), out_matrix.data(), n_cols);

    puts("\n'In matrix' after gf_invert_matrix:");
    print_matrix(in_matrix, n_rows, n_cols);
}
$ g++ test.cpp -o a -lisal
$ ./a
```

### Expected

```
'In matrix' before gf_invert_matrix:
01 01 01
01 01 01
01 01 01

'In matrix' after gf_invert_matrix:
01 01 01
01 01 01
01 01 01
```

### Actual

```
'In matrix' before gf_invert_matrix:
01 01 01
01 01 01
01 01 01

'In matrix' after gf_invert_matrix:
01 01 01
00 00 00
00 00 00
```

## Version

`2.28.0`

**Comment by gbtucker** [comment]
Yes thanks for pointing out.  This is a limit in the documentation.  The gf_invert_matrix() does destroy the input matrix and the documentation should reflect.
