### ISSUE TITLE
The build wont use yasm

### ISSUE THREAD

**Issue by davesiddons** [intel/isa-l#124]
As part of CentOS 7.7 we have the wrong version of nasm installed but the correct version of yasm. Even so, the build tries to use nasm and fails

**Comment by gbtucker** [comment]
Thanks for reporting the issue.  What version of nasm is installed?  Are you building with autoconf?

The build should check your nasm for feature availability and the test code is selected to also exclude known nasm bugs.  Autoconf will choose the nasm or yasm with better feature support but the std. makefile will only check the one you specify, nasm being the default.

**Comment by davesiddons** [comment]
We have 2.10 as defaulted with CentOS 7.7.  We dont use autoconf. I tried using the standard makefile and it defaulted to nasm. Could you advise where this is specified. Cheers

**Comment by gbtucker** [comment]
It is specified at: https://github.com/intel/isa-l/blob/fae4c3a4994f894bf57adafa18ed310d145ab1b0/make.inc#L52
You can do `make -f Makefile.unx AS=yasm` but I'd suggest updating your nasm as you get the lastest avx512 versions.

**Comment by davesiddons** [comment]
Thanks gbt, help much appreciated
