### ISSUE TITLE
SYNC_FLUSH on inflate

### ISSUE THREAD

**Issue by brandonto** [intel/isa-l#126]
Hey guys, this is not really an issue as much of a question...

zlib has a Z_SYNC_FLUSH flag on both the inflate and deflate function to tell the library to flush all pending output to the output buffer.

I've noticed that igzip only supports SYNC_FLUSH on the deflate side. Are there any compatibility concerns with zlib on the inflate side?

**Comment by gbtucker** [comment]
The SYNC_FLUSH and FULL_FLUSH have the same affect as the corresponding zlib flags.  There shouldn't be any compatibility issues.  Just like in zlib, they are really to ensure a new block is created and output aligned.  From the ISA-L doc.

```
 A SYNC_ OR FULL_ flush will byte align the deflate block by appending an empty stored block once
 all input has been compressed, including the buffered input. Checking that the out_buffer is not
 empty or that internal_state.state = ZSTATE_NEW_HDR is sufficient to guarantee all input has been
 flushed. Additionally FULL_FLUSH will ensure look back history does not include previous blocks so
 new blocks are fully independent. 
```

**Comment by brandonto** [comment]
> The SYNC_FLUSH and FULL_FLUSH have the same affect as the corresponding zlib flags. There shouldn't be any compatibility issues. Just like in zlib, they are really to ensure a new block is created and output aligned. From the ISA-L doc.
> 
> ```
>  A SYNC_ OR FULL_ flush will byte align the deflate block by appending an empty stored block once
>  all input has been compressed, including the buffered input. Checking that the out_buffer is not
>  empty or that internal_state.state = ZSTATE_NEW_HDR is sufficient to guarantee all input has been
>  flushed. Additionally FULL_FLUSH will ensure look back history does not include previous blocks so
>  new blocks are fully independent. 
> ```

How can we set the SYNC_FLUSH flag on the call to inflate?

**Comment by gbtucker** [comment]
There is no corresponding flag for decompression in ISA-L.  From the zlib manual: "Z_SYNC_FLUSH requests that inflate() flush as much output as possible to the output buffer."  In ISA-L decompression we always push as much as possible.

**Comment by brandonto** [comment]
Thanks, this answers my question. It wasn't clear to me when reading the header file.
