### ISSUE TITLE
igzip can not read concatenated gzip files.

### ISSUE THREAD

**Issue by rhpvorderman** [intel/isa-l#143]
This prevents it from becoming a drop-in replacement for gzip.

gzip's behavior:
```
$ echo bla | gzip -c > test.gz
$ echo bla | gzip -c >> test.gz
$ gzip -cd test.gz 
bla
bla
```

igzip is able to create proper concatenated `.gz` files but cannot fully read them:
```
$ echo bla | igzip -c > test.gz
$ echo bla | igzip -c >> test.gz
$ gzip -cd test.gz 
bla
bla
$ igzip -cd test.gz 
bla
```

It can also not read concatenated `.gz` files from gzip:
```
$ echo bla | gzip -c > test.gz
$ echo bla | gzip -c >> test.gz
$ gzip -cd test.gz 
bla
bla
$ igzip -cd test.gz
bla
```

I was on my way to adding igzip to [xopen](https://github.com/marcelm/xopen) but unfortunately this causes our tests to fail. 

EDIT: Whoops forgot the version:
```
igzip --version
igzip command line interface 2.29.0
```

**Comment by gbtucker** [comment]
Thanks for integrating into xopen.  I can look into adding the concatenated gzip feature to the cli.

**Comment by rhpvorderman** [comment]
Thanks for looking into it! I work in bioinformatics and unpacking of 10GB+ (even 100GB+) gzipped FASTQ files happens daily (all automated). We would love to speed this up with igzip but we have no way to be certain if our input files are concatenated or not. So we have to stick with `pigz -cd` for the moment as the fastest way to unpack these files. Fixing igzip's behaviour would be a huge compute-time saver for us!

**Comment by gbtucker** [comment]
That's great.  I should have a prototype to test on soon.

**Comment by gbtucker** [comment]
@rhpvorderman, I have a prototype of igzip with concat .gz if you wish to pre-test.

**Comment by rhpvorderman** [comment]
Sure! If you have a git branch for me I can build and test it.
Thanks for following up so quickly.

**Comment by rhpvorderman** [comment]
Thanks! This is great. I tested the PR with the following zip file.
``` bash
# Get 5G of random characters 
$ cat /dev/urandom | base64 | head -c 5G | gzip -c > big_concatenated.gz
# Concatenate 5G of random characters 
$ cat /dev/urandom | base64 | head -c 5G | gzip -c >> big_concatenated.gz
$ gzip -l big_concatenated.gz
         compressed        uncompressed  ratio uncompressed_name
         8074856623          1073741824 -652.0% big_concatenated
```
The compression ratio is all off. This is a known problem with gzip headers storing the file sizes as 32-bit and not handling stuff above 4G well. That is why I used two times 5G of characters. igzip should be able to handle this edge case as well. This is relevant in real life for concatenated DNA data in the form of FASTQ files! These are also often multiple gigabytes.

```
# Test pigz. Written by the zlib maintainer Mark Adler. 
$ pigz -cd  big_concatenated.gz | wc -c 
10737418240
```
Correct !
```
# test igzip build from @gbtucker's branch
$ igzip -cd big_concatenated.gz | wc -c
10737418240
```
Also correct!

For comparison test the version in Debian 10 (buster) repo.

```
$ igzip --version
igzip command line interface 2.25.0
$ igzip -cd big_concatenated.gz | wc -c
```
This is stuck in a loop forever. That is a severe bug.

Test the latest stable version from conda.
```
$ igzip --version
igzip command line interface 2.29.0
$ igzip -cd big_concatenated.gz | wc -c
```
Also stuck in endless loop.

Your PR is a great fix.
