### ISSUE TITLE
I'm in trouble, Gangster help me！！！When using command "make -f Makefile.unx" ,it will have a error.

### ISSUE THREAD

**Issue by JIQ1314an** [intel/isa-l#153]
[root@compile-test0 isa-l]# make -f Makefile.unx
---> Building erasure_code/ec_multibinary.asm  x86_64 
multibinary.asm:283: error: expression syntax error
multibinary.asm:359: error: expression syntax error
make: *** [bin/ec_multibinary.o] Error 1

**Comment by gbtucker** [comment]
Perhaps the version of nasm is too old. Can you check with $nasm --version

**Comment by JIQ1314an** [comment]
[root@compile-test0 ~]# nasm -version
NASM version 2.10.07 compiled on Jun  9 2014

Is  this  version   old?

**Comment by JIQ1314an** [comment]
Seems a bit old ，
The document says ，
x86_64:
Assembler: nasm v2.11.01 or later (nasm v2.13 or better suggested for building in AVX512 support) or yasm version 1.2.0 or later.

**Comment by JIQ1314an** [comment]
I installed  nasm and yasm   directly using  command  yum

**Comment by JIQ1314an** [comment]
This problem had  solved. Thank you, gbtucker!
