### ISSUE TITLE
Hadoop 3.2.1 ErasureCoding ISA-L Question?

### ISSUE THREAD

**Issue by isurika4** [intel/isa-l#154]
I am testing hadoop 3.0 Erasure coding.. For the test, I uploaded 100GB in hadoop 3.2.1, and the results were shown below. (5 datanode)

3 COPY : 150 minute
E C : 250 minute (RS-3-2-1024k)

To increase the speed of the EC by applying ISA-L, I set it up and tested the operation, but the speed came out the same.
# hadoop checknative
ISA-L: true /lib64/libisal.so.2

(1) it is an old device, so I wonder if the CPU does not support it. Where can I check the list of CPUs that support ISA-L?
CPU : Intel(R) Xeon(R) CPU E5-2609 v2 @ 2.50GHz

(2) Please advise if there is a method of applying ISA-L to be added.

**Comment by gbtucker** [comment]
On (1) the cpu does have AVX so there are some optimized functions for EC.  Certainly just the step to AVX2 could see a potential jump in throughput though but not sure if EC calculation is the bottleneck.  A profile could clear this up.

On (2) I'm not an expert on HDFS configuration so I'm not sure that just the dynamic linker search will ensure it is being used.

**Comment by isurika4** [comment]
Thank you!!!
I have additional questions
(1) Is support available on this CPU?
----------------------------------------------
  Intel(R) Xeon(R) CPU E5620 @ 2.40GHz
----------------------------------------------
(2) Before and after using ISL on Linux (Cents8)
I want to know how to test performance.

**Comment by isurika4** [comment]
> On (1) the cpu does have AVX so there are some optimized functions for EC.  Certainly just the step to AVX2 could see a potential jump in throughput though but not sure if EC calculation is the bottleneck.  A profile could clear this up.
> On (2) I'm not an expert on HDFS configuration so I'm not sure that just the dynamic linker search will ensure it is being used.

**Comment by isurika4** [comment]
Thank you!!!
I have additional questions
(1) Is support available on this CPU?
Intel(R) Xeon(R) CPU E5620 @ 2.40GHz
(2) Before and after using ISL on Linux (Cents8)
I want to know how to test performance.

**Comment by gbtucker** [comment]
@isurika4, there are multiple optimized versions for EC functions in ISA-L including for machines with and without vector instructions.  You can check for supported instruction set on ark.intel.com.  The machine in [(1)](https://ark.intel.com/content/www/us/en/ark/products/47925/intel-xeon-processor-e5620-12m-cache-2-40-ghz-5-86-gt-s-intel-qpi.html) has sse4.2 so yes, it will use optimizations written around these.
You can try the included performance tests for micro-benchmarks on Linux.
