### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by rhpvorderman** [intel/isa-l#155]
I like this library a lot. I think it would be great if this would be used more. I work as a bioinformatician and in my field we use a lot of zlib-compatible compression. We also tend to use python a lot.

Therefore I have created python-bindings for this library https://github.com/rhpvorderman/python-isal .

I post it here so there may not be duplication of effort. The library is not production ready at this moment, a lot more tests need to be added to make sure most production use cases are covered and all obvious bugs are squashed. However, everything seems to work, so people want to play with it/benchmark it, can use it already.

I will add a comment when I am releasing version 0.1.

**Comment by gbtucker** [comment]
That's great thanks!  We can add a language bindings section to the wiki when ready.

**Comment by rhpvorderman** [comment]
I believe there are already java bindings available. Provided by intel on the [Genomics Kernel Library](https://github.com/Intel-HLS/GKL). The source files for the Java Native Interface are [here](https://github.com/Intel-HLS/GKL/tree/master/src/main/native/compression).

Unfortunately, these bindings are not very good. And benchmark results do seem to depend on which processor is used https://github.com/broadinstitute/picard/pull/1541. The resulting filesizes do seem to get 20-30% bigger as the standard Java Deflater on compression level 1. Which is a bit weird. 

Maybe it will get better if the isa-l libraries get their own isa-l-java implementation?

**Comment by rhpvorderman** [comment]
I have released a 0.1.0 version of the python bindings https://pypi.org/project/isal/ . The gzip functionality should now be available to python users.

**Comment by rhpvorderman** [comment]
Closing this as python bindings can be found here https://github.com/pycompression/python-isal.
