### ISSUE TITLE
How to compile ISA-L with AVX-512 support?

### ISSUE THREAD

**Issue by g199209** [intel/isa-l#160]
I found that EC calculation support AVX-512 from the source code, but I can't found how to enable it.

The related code has a conditional compile flag `HAVE_AS_KNOWS_AVX512`, how can I define this macro?

I have checked the `./configure --help`, but can't found anything about AVX-512.

Note:
The compile enviroment I used:
```
NASM version 2.14.02 compiled on Sep  2 2019
gcc (GCC) 9.3.0
```

**Comment by gbtucker** [comment]
There are configure tests that set this flag based on the assembler output of test code.

    AC_MSG_CHECKING([for optional nasm AVX512 support])
    AC_LANG_CONFTEST([AC_LANG_SOURCE([[vinserti32x8 zmm0, ymm1, 1;]])])

Seems like your nasm version should be adequate unless there are particular issues with that build.  You might try the test.
`echo vinserti32x8 zmm0, ymm1, 1\; > tst.asm && nasm -f elf64 tst.asm && echo pass`
or look in the ./configure output for the test result.
```
checking for nasm... yes
checking for modern nasm... yes
checking for optional nasm AVX512 support... yes
checking for additional nasm AVX512 support... yes
Using nasm args target "linux" "-f elf64"
```

**Comment by g199209** [comment]
@gbtucker Thanks! I found AVX512 is already enabled in my configuration. And I checked the `ec_encode_data()` function, this function already called AVX512 version at the runtime. :)
