### ISSUE TITLE
AVX512 instructions CPU declocking 

### ISSUE THREAD

**Issue by showvick** [intel/isa-l#161]
I was wondering if compress deflate/inflate with level 2 use AVX512 instructions? 

        isal_deflate_stateless_init(&isalstream);
        isalstream.end_of_stream = 1;
        isalstream.flush = NO_FLUSH;
        isalstream.next_in = (Bytef *)cmpinstart_p;
        isalstream.avail_in = bytestocompress;
        isalstream.next_out = (Bytef *)cmpoutstart_p;
        isalstream.avail_out = length;
        isalstream.gzip_flag = IGZIP_ZLIB;

        isalstream.level = 2;
        isalstream.level_buf = blkalloc(NULL, 1, ISAL_DEF_LVL2_DEFAULT);
        isalstream.level_buf_size = ISAL_DEF_LVL2_DEFAULT;

        zret = isal_deflate_stateless(&isalstream);

I did see usage in the executable with regard to AVX512, but wasn't sure if it was specific to deflate/inflate level 2. 
   1e73d:       62 d1 7f 48 6f 04 01    vmovdqu8 (%r9,%rax,1),%zmm0
   1e748:       62 f1 fd 48 db cd       vpandq %zmm5,%zmm0,%zmm1
   1e74e:       62 f1 7d 48 71 e0 04    vpsraw $0x4,%zmm0,%zmm0
   1e755:       62 f1 fd 48 db c5       vpandq %zmm5,%zmm0,%zmm0
   1e773:       62 f2 65 48 00 d8       vpshufb %zmm0,%zmm3,%zmm3
   1e7da:       62 f1 75 48 71 e0 04    vpsraw $0x4,%zmm0,%zmm1
   1e7e1:       62 f3 fd 48 43 c1 44    vshufi64x2 $0x44,%zmm1,%zmm0,%zmm0
   1e7e8:       62 f1 fd 48 db c5       vpandq %zmm5,%zmm0,%zmm0
   1e7ff:       62 f2 5d 48 00 e0       vpshufb %zmm0,%zmm4,%zmm4

With Intel's IPP version of deflate/inflate we did see declocking of CPU leading to increased usage. 
IPP provides  ippSetCpuFeatures API to disable AVX 512 
https://software.intel.com/content/www/us/en/develop/documentation/ipp-dev-reference/top/volume-1-signal-and-data-processing/support-functions/common-functions/setcpufeatures.html 

Is there a similar call to disable AVX512 in isal? 

Thanks in advance.

**Comment by gbtucker** [comment]
ISA-L inflate does not use AVX512 instructions.  ISA-L deflate level 1 and above can employ AVX512.  Level 0 does not.

There is no run-time disable for particular instruction sets or to set versions.  It is possible to compile the library without, `make -f Makefile.unx as_feature_level=4` for example, but I suggest you test first with the highest versions.

**Comment by showvick** [comment]
Thanks for the prompt response. We will test it out.
