### ISSUE TITLE
Redistributing a statically linked version of isal in language binding libraries

### ISSUE THREAD

**Issue by rhpvorderman** [intel/isa-l#171]
Hi as you know I have created the [python bindings for isal](https://github.com/pycompression/python-isal). I have had some discussion with the xopen (for python) developer about the best way to redistribute python-isal. 

It seems that the most convenient way for users will be a statically linked package. That way they do not require the isa-l libraries installed on their system and they do not need to bother with complex installation requirements. A simple `pip install isal` is sufficient.

My question is how I go about doing this without violating the license requirements:

```
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in
      the documentation and/or other materials provided with the
      distribution.
    * Neither the name of Intel Corporation nor the names of its
      contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
```

I can make the python redistributable package so that:

- It includes a README that states that a version of isa-l is included as a statically linked package. With a reference to the isa-l license.
- The package includes the source files of the isa-l distribution (at least the once that are used)
- The package includes the license of the isa-l distribution
- The package includes the binary blob with the necessary isa-l functionality and the binding functionality.

I think that would be compliant with the license. What is your opinion about this?

**Comment by gbtucker** [comment]
@rhpvorderman, Thanks for your work on python-isal.  I'm not sure where the license needs to go.  I know a lot of projects link with isa-l as a static library.  Perhaps it would help to review other projects or distros that do.

**Comment by rhpvorderman** [comment]
Hi. I checked it out in the Genomics Kernel Library, and could not find anything really. So I tried it on my own: https://github.com/pycompression/python-isal/pull/23. 

I provided a source tarball with the distribution.  This contains both the source and the license. I also added a LICENSE file besides the source tarball so people who cannot open tar files can read it. I also added a README file linking to this github page. While adding the source is not required by this license, I think it is a nice thing to do in free/libre software (The GPL requires it for example).

I suppose this is in compliance with the license. I could add a `license()` function that reproduces the license to the python code but that feels a little excessive. I have taken much care to credit isa-l in the README and the code as well. If there are any concerns with python-isal not complying with the license, please contact me!

Thanks again for your great work on this project. Speeding up bioinformatics workloads means helping more patients!

**Comment by rhpvorderman** [comment]
I managed to statically link isa-l in the binary packages for isa-l. Binaries can be found on the download page on pypi (https://pypi.org/project/isal/).  I included the isa-l LICENSE, README and Release_notes.txt in the binary distribution. If there are any problems regarding this way of distributing, feel free to contact me.
