### ISSUE TITLE
A potential bug about xor_gen_base() function in raid_base.c?

### ISSUE THREAD

**Issue by pchengma** [intel/isa-l#175]
I am writing a program using the **xor_gen_base()** function in **raid_base.c** file, but I meet an issue. The details are as follows.  

```
int xor_gen_base(int vects, int len, void **array)
{
	int i, j;
	unsigned char parity;
	unsigned char **src = (unsigned char **)array;

	for (i = 0; i < len; i++) {
		parity = src[0][i];
		for (j = 1; j < vects - 1; j++)
			parity ^= src[j][i];

		src[vects - 1][i] = parity;	// last pointer is dest

	}

	return 0;
}
```
Here is the source code of xor_gen_base() function. From the source code, if **vects == 2**, **the src[1][i] should be equal to src[0][i], where i is the column iteration index**, which means the result should be the original data without XOR. However, from my testing, this is not the case.

```
#include <stdio.h>
#include <stdint.h>

#include "raid.h"

int main() {
    int i, j;
    int vects = 2, len = 1;

    uint8_t **array = (uint8_t **) malloc(sizeof(uint8_t *) * vects);
    for (i = 0; i < vects; ++i) {
        array[i] = (uint8_t *) malloc(sizeof(uint8_t) * len);
    }
    for (i = 0; i < vects; ++i) {
        memset(array[i], 0u, len);
    }

    for (i = 0; i < vects - 1; ++i) {
        for (j = 0; j < len; ++j) {
            array[i][j] = 5u; // just some randomly chosen number
        }
    }

    // Print original array:
    printf("\narray values:\n");
    for (i = 0; i < vects; ++i) {
        for (j = 0; j < len; ++j) {
            printf("%d\t", array[i][j]);
        }
        printf("\n");
    }

    // Perform xor_gen():
    xor_gen(vects, len, array);


    // Print array after xor_gen:
    printf("\narray values:\n");
    for (i = 0; i < vects; ++i) {
        for (j = 0; j < len; ++j) {
            printf("%d\t", array[i][j]);
        }
        printf("\n");
    }

    return 0;
}
```
Here is the testing program for xor_gen_base(). I set vects as 2 for testing and len as 1 for convenience. Then, I randomly set a value to the first row of array (here the value is 5). Next, I print out the original values of array. Then, I call xor_gen(vects, len, array) where xor_gen() is a function defined in raid.h that directly calling xor_gen_base(). Finally, I print out the result array.

![xor_gen_bug](https://user-images.githubusercontent.com/46284365/115552513-0201a100-a2df-11eb-8ba4-7cfdc8057bb7.png)
However, from the output figure. **The last row is still zero, rather than 5**. Is this a bug for the xor_gen() function? Moreover, when vects > 2, the function works well.

**Comment by gbtucker** [comment]
We didn't consider the case of doing xor over 1 source.  In fact the asm versions all check for a minimum of 2 for source + dest.
```
func(xor_gen_avx512)
        FUNC_SAVE
        sub     vec, 2                  ;Keep as offset to last source
        jng     return_fail             ;Must have at least 2 sources
```
Note the comment is not quite right here since 2 is for one source and one dest so minimum of 1 source.  The base function should have done the same thing and include a check.  Also the documentation should have specified that you need to have more than one source.  I'm not sure it makes sense to have a 1 source xor function that turns into memcpy.  Likewise the pq_gen functions must have at least two sources.

**Comment by pchengma** [comment]
@gbtucker Thanks for your reply. I think your explanation is very good that xor_gen() should be used with at least two sources and a check is necessary when we use xor_gen() in our program.
