### ISSUE TITLE
About environment variable D

### ISSUE THREAD

**Issue by cielavenir** [intel/isa-l#184]
I have found that `D=name=value make` can be used to set additional define. It is used in make.inc `DEFINES += $(addprefix -D , $D)` and Makefile.am `AM_CFLAGS = ${my_CFLAGS} ${INCLUDE} $(src_include) ${D}` (oh actually Makefile.am syntax is inconsistent with make.inc). Could you tell me the usecase?
I'm sure python-isal's build system has no usecase so I'm suggesting removing it in https://github.com/pycompression/python-isal/pull/92, but I'm interested in isa-l itself.

In our case, I found that `export D=/path/to/detection` causes build error.

/cc @rhpvorderman

**Comment by gbtucker** [comment]
@cielavenir, It is a shortcut for adding additional defines without changing other flags.  We can change it but some internal and included tools rely on it such as the test scripts in /tools/test_*.sh.  Perhaps we can just override the environment variable by presetting to null and then only the command line can override.  Please see linked PR.
