### ISSUE TITLE
brew install isa-l

### ISSUE THREAD

**Issue by ankane** [intel/isa-l#193]
Hi, thanks for this library! Just wanted to share that it's now available on Homebrew, so Mac x86_64 users can install it with:

```sh
brew install isa-l
```

Once #164 is resolved, Mac arm64 users can use this method as well.

Ref: https://github.com/Homebrew/homebrew-core/pull/90537

**Comment by gbtucker** [comment]
Thanks @ankane!  That's great.  I'll add it to the repo list.

**Comment by ankane** [comment]
Awesome, thanks @gbtucker!
