### ISSUE TITLE
Why smaller chunksize Erasure Coding has better throughput?

### ISSUE THREAD

**Issue by mengwanguc** [intel/isa-l#203]
Hello,

I'm running `erasure_code/erasure_code_perf` with different `[GT_L3_CACHE](https://github.com/intel/isa-l/blob/master/erasure_code/erasure_code_perf.c#L46)`.
And I find that different `GT_L3_CACHE` provides different bandwidth.

For example, when `GT_L3_CACHE` = 128 * 1024 (128KB), the encode bandwidth is 11148.94 MB/s
However, when `GT_L3_CACHE` = 32 * 1024 * 1024 (32MB), the encode bandwidth is 9958.72 MB/s.

Why is this happening? Shouldn't they require same number of computations for each data unit since they are both doing (10+4) Erasure Coding? Is this related to L3 cache etc?

Thanks in advance!

**Comment by gbtucker** [comment]
Hi @mengwanguc.  Most of the benchmarks have a CACHED_TEST and uncashed test option where the latter will loop over a large dataset and should force loads from main memory (if GT_L3_CACHE is at least larger than the last level of cache in the system).  While not perfect, these "warm" and "cold" cache tests can give some ideas about the limits in the system.  If you intentionally decrease the data set size to lower than last level cache size you defeat the intention of the "cold" test.  Note that even in the "cold" case, HW prefetchers are working ahead and in some cases (high cycles-per-byte functions) the "warm" and "cold" performance is similar.

**Comment by mengwanguc** [comment]
Thanks @gbtucker! To follow up, I'm wondering what will happen in real storage systems. 
Let's say we want to encode 128KB data which is smaller than L3 cache. Will it always have similar performance as "warm" cache tests, or is it possible that it may read from RAM and thus have worse cold performance?

**Comment by mengwanguc** [comment]
I think in real systems the performance will be worse than the performance tests for small datasets like 128KB. Because the benchmark keeps doing erasure coding on the same dataset again and again, and that dataset will stay in cache. However, in real system it won't happen because each dataset is only encoded once.

If that's the case, is it possible to benchmark encode performance for small datasets in isa-l?

**Comment by gbtucker** [comment]
These are micro-benchmarks and how it performs in a real system depends on good system design.  It is possible with placement, blocking, prefetch, cache allocation or other means to have data ready in cache when an encode is performed.  The only way to really know is to integrate and use system performance tools to analyze.
