### ISSUE TITLE
Do we need to call gf_gen_rs_matrix and ec_init_tables for every erasure coding job?

### ISSUE THREAD

**Issue by mengwanguc** [intel/isa-l#208]
Suppose we are doing 10+4 erasure coding for different data matrix A, B, C. And suppose A, B, C have the same amount of data.

Before doing erasure coding, we need to call `gf_gen_rs_matrix(a, m, k)` and `ec_init_tables(k, m - k, &a[k * k], g_tbls)`

My questions is, after we've initialized g_tbls for data A, can we use the same g_tbls to encode B and C?

In other words, do we need to initialize g_tbls once, or three times?

Thanks!

**Comment by gbtucker** [comment]
No, normally you only have to pick the encoding matrix coefficients (and expand the coefficients) once and then reuse for many, many encode cycles.  You only have to re-run `ec_init_tables()` if you have changed the coding matrix, not if you just change the data input to encode, and there is usually little reason or none to ever change the coding matrix once you pick one.

**Comment by mengwanguc** [comment]
Thanks!
