### ISSUE TITLE
For erasure coding can we have more parity than data

### ISSUE THREAD

**Issue by mengwanguc** [intel/isa-l#209]
I'm running [erasure_code_perf.c](https://github.com/intel/isa-l/blob/ebb78fc99ef7247bd9c16cecf7faa248563ce4f6/erasure_code/erasure_code_perf.c)

I found that the decoding always fails when k < m - k, where k is the number of data units.
For example, when m = 10 and k = 4, we are doing (4+6) erasure coding. The encoding works but the decoding always fail.

Is it a limitation of isa-l erasure coding implementation, or a limitation of Reed-Solomon erasure coding itself?
Can we have more parities than data units?

Thanks!

**Comment by jeffareid** [comment]
It's not an issue for Reed Solomon erasure coding (redundancy is parities) or Raid type coding (redundancy is syndromes). I've never looked at the code used in intei/isa-l/erasure _code, so I don't know what coding method is being used, but this shouldn't be an issue, so the failure is specific to this particular implementation.

**Comment by gbtucker** [comment]
There are no such restrictions in isa-l erasure_code.  isa-l works with any encoding matrix and can generate any number of parity and from any number of sources.  (m=255 is practical limit in gf(2^8) however).

The performance test is intended to be simple at the expense of being specific.  When you want to re-generate columns of sources *and* parity you need one extra step to generate the decoding matrix.  See https://github.com/intel/isa-l/blob/master/examples/ec/ec_simple_example.c#L264.  Note the error list in the performance test is all sources, no parity so this step is not necessary.  In your case you can change the list to `err_list[] = { 0, 1, 2, 3 }` or add a step to multiply the encode matrix * invert matrix as in `ec_simple_example.c`.

**Comment by mengwanguc** [comment]
thanks!
