### ISSUE TITLE
question about read amplification in erasure encoding

### ISSUE THREAD

**Issue by GrayXu** [intel/isa-l#216]
To the best of my knowledge, ISA-L erasure coding with AVX512 is a loop like below:  

1. read data in 512bit granularity
2. do vect_dot_prod
3. save result in 512bit regs

And finally write results to DRAM. So there is only one read for data, and one write for parity. (which is cache friendly)

But the [pcm-memory](https://github.com/opcm/pcm), a memory controller throughput monitor, shows that there are more than one reads.

for example, encoding 4 data blocks to 2 parity blocks should introduce make the read/write throughput ratio 2:1. But the results shows that it is bigger than 4:1...

Do I have some misconceptions about the coding process?

Note: 
- Both data and parity are contiguous
- Disabling hardware cache prefetching will have no effect
- Working set of about a few GB.

Env: ISA-L 2.30.0, Ubuntu 16, Xeon(R) Gold 6240

thanks!

**Comment by gbtucker** [comment]
ISA-L erasure code routines do run in a loop and functions such as `ec_encode_data()` can calculate up to 6 parity in each pass of the input sources.  So for your example of 4 source and 2 parity and using `ec_encode_data()` it should do 4 reads and 2 writes per loop.  I'm not sure how the pcm-memory util is counting.
