### ISSUE TITLE
Wrong version of MSV CRT linked in static Windows build

### ISSUE THREAD

**Issue by zbjornson** [intel/isa-l#219]
Hello - These lines set `/MD{d}` for both static and dynamic builds, but I think static should be using `/MT{d}`.

https://github.com/intel/isa-l/blob/8b7c1b80b22833e0629ccf00e62fda6b3884c7ae/Makefile.nmake#L170-L171

Trying to statically link this to library causes `warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs`.

**Comment by gbtucker** [comment]
Thanks @zbjornson.  Now I'm not sure why these options are in there at all.  They are more linker options anyway and don't seem necessary to build the unit tests.  I can submit a PR to remove them and we can collect feedback there.

**Comment by gbtucker** [comment]
@zbjornson, could you possibly test against the PR #220?

**Comment by zbjornson** [comment]
Tested, that resolves it, thanks for the fast fix @gbtucker!
