### ISSUE TITLE
slversion macro puts data into the text section

### ISSUE THREAD

**Issue by fenrus75** [intel/isa-l#221]
in include/reg_sizes.asm:
%macro slversion 4
	section .text
	global %1_slver_%2%3%4
	global %1_slver
	%1_slver:
	%1_slver_%2%3%4:
		dw 0x%4
		db 0x%3, 0x%2
%endmacro

this is putting data into the .text section... which is confusing various tools and isn't great all around.
does anyone know why this wasn't ".rodata"  (and a .previous at the end of it)

**Comment by gbtucker** [comment]
A relic I can remove.
