### ISSUE TITLE
why not merge ec_encode_data_mbinit and ec_encode_data into a single function?

### ISSUE THREAD

**Issue by HShan886** [intel/isa-l#230]
Hi, 
 `.quad   \name\()_mbinit         //func_entry` in [include](https://github.com/intel/isa-l/tree/master/include)/aarch64_multibinary.h, such as ec_encode_data_mbinit, hasn't return or terminator instruction. So gcc/llvm compiler will consider these code as a function. However, in function schedule algorithm, the two functions are splitted into different location. Then will result in segment fault.

**Comment by gbtucker** [comment]
I was hoping the arm team would comment on this.  Can you put more details about what system this is seg faulting on?  I'm not sure why the arm dispatcher function is in the .data segment but this seems to work on many systems.

**Comment by Haishan312** [comment]
@gbtucker thank you.  I am using hfsort algorithm to schedule functions. Then the two functions are splitted into different locations. Like:
```
ec_encode_data_mbinit
// other funcitons
ec_encode_data
```
when ec_encode_data_mbinit runs over, program would run other functions instead of ec_encode_data.

**Comment by gbtucker** [comment]
OK, do you mention aarch64_multibinary.h because you are running on arm?  Seems the dispatcher has the same name in x86 and arm.  If so does hfsort work on isa-l under x86_64 platforms?

**Comment by Haishan312** [comment]
> OK, do you mention aarch64_multibinary.h because you are running on arm? Seems the dispatcher has the same name in x86 and arm. If so does hfsort work on isa-l under x86_64 platforms?

Yes， this optimization is running under aarch64 platform

**Comment by gbtucker** [comment]
I see the issue.  Perhaps the 4 instructions for dispatch could be repeated at the end of _mbinit so as to not rely on the fall-through to the dispatch function.  This way the functions could be separated by the linker any way hfsort specifies.  Merging them may be more difficult as the dispatcher calls a pointer to a function so they must both be functions.
