### ISSUE TITLE
Can I run ISA-L erasure coding APIs without Intel CPU's H/W acceleration?

### ISSUE THREAD

**Issue by junghyun-34** [intel/isa-l#231]
Hi, I'm working on my project using ISA-L's erasure coding APIs and It works very nicely.
I want to report how accelerated my ISA-L based RAID6 on my XEON CPU. 
Is there a baseline version of erasure coding that can run ISA-L without Intel CPU acceleration such as AVX or SSE? 
It would be great If I can clearly see the performance improvement between ISA-L vs C/C++ ver. APIs.
Thanks,

**Comment by gbtucker** [comment]
Hi @junghyun-34.  Yes, all the functions in isa-l have base versions that are written to be portable and run nearly anywhere.  They may be selected by the dispatcher if there are no vector instructions available.  You can look for `ec_encode_data_base()` for example or for many other functions `func()` you can find `func_base()`.

**Comment by junghyun-34** [comment]
Thanks!!!!!
