### ISSUE TITLE
Does isa-l only support assemble code building or it can be compiled by pure c code?

### ISSUE THREAD

**Issue by Fanyuanli** [intel/isa-l#233]

**Comment by Fanyuanli** [comment]
ISA-L is said to have a good performance because it uses assembly code. Can I compile this library using only C code? According to my verification, it should be possible. In this case, does it mean that ISA-L can run on multiple platforms? Which of these two ways is better? Thank you so much!

**Comment by gbtucker** [comment]
Hi @Fanyuanli.  I would suggest that you get a modern assembler (nasm for x86, gas for Arm) when you build isa-l for the best performance but it is possible to build with base functions C only.  Either way isa-l can run on multiple platforms.

**Comment by Fanyuanli** [comment]
Thanks a lot for your advice! I'd like to take a try.

**Comment by Fanyuanli** [comment]
I have done my test and verified your suggestions. And I think I've got what I wander. Thanks again! @gbtucker
