### ISSUE TITLE
Make new release? Last release 2.30.0 was >2 years ago, previously releases every few months

### ISSUE THREAD

**Issue by corneliusroemer** [intel/isa-l#234]
I noticed that you seem to have stopped releases 2 years ago - before then you released at least once every year.

What's the reason for this? The repo still seems actively maintained but without release the features don't become available through conda-forge etc.

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/25161793/218769930-f3cddcdf-121a-4aa6-90a4-9d1261428780.png">

**Comment by gbtucker** [comment]
As far as conda-forge I think @rhpvorderman helped some of this by rolling in 2.30.0+ commits but I agree overdue for a release.

**Comment by corneliusroemer** [comment]
Great, thanks! It's through him that I ended up looking at ISA-L as he mentioned a release is one of the things blocking isa-l being supported on osx-arm through conda-forge which would be neat (the other is lack of hardware for him, but maybe someone else can help).

**Comment by rhpvorderman** [comment]
> As far as conda-forge I think @rhpvorderman helped some of this by rolling in 2.30.0+ commits but I agree overdue for a release.

I did that only in the python bindings. The commits in question are only the ones to give windows an isa-l.h header file and to fix the zlib wrapper bug. These are not really crucial for day-to-day operation (who uses less than 15 wbits?) but were important for the python-isal bindings to obtain drop-in replacement status for CPython's zlib module. I guess I could patch ISA-L with the zlib wrapper fix as well on conda-forge.

**Comment by rhpvorderman** [comment]
What are the blockers for a release? I understand that ISA-L is quite mature at this point, but it has been almost 3 years since the last release. I understand that there may be time or other constraints. If I know what the blockers are maybe I can do a few things to help out.

**Comment by pablodelara** [comment]
Hi @rhpvorderman. There has been a team change at Intel working at this project and we are currently ramping up on it. We are working towards releasing around Q1 next year. Is this timeframe OK?

**Comment by rhpvorderman** [comment]
@pablodelara Thanks for the information. Any timeframe is OK with me. I am glad you are still actively maintaining the project.

**Comment by pablodelara** [comment]
Closing this issue, as we are releasing a new version this month.
