### ISSUE TITLE
error checking for avx512 support

### ISSUE THREAD

**Issue by prton12138** [intel/isa-l#241]
I compile this library on a machine which supports avx512.But configure didn't check avx512 correctly.
It checks avx512 on nasm like "vinserti32x8 zmm0, ymm1, 1".
But in fact, this instruction works like "VINSERTI32X8 zmm1 {k1}{z}, zmm2, ymm3, 1" on my machine.
I run a simple example as follow.
![image](https://user-images.githubusercontent.com/67046461/235375336-c6f727df-627c-46bb-9b10-765865fc1a65.png)

**Comment by pablodelara** [comment]
Well, shouldn't your file be .asm and not .c? Anyway, that second instruction looks OK. Which NASM version are you using?

**Comment by prton12138** [comment]
I check the version of nasm, which is the reason of invalid instruction. Thanks for your help.

**Comment by pablodelara** [comment]
Perfect, good to know. Closing the issue.
