### ISSUE TITLE
compressed data by igzip cannot be decoded

### ISSUE THREAD

**Issue by BeeBreeze** [intel/isa-l#245]
Recently, our company is writing some wrapper to replace zlib with igzip. Just now, I found a 4B length data, 0x45449044, whose compressed data is 12B length, 0x7801727599e002000000ffff, with igzip lvl 1. The question is that, when decompressing the 12 Bytes, with zlib, the return value of inflate() is -3, and the error msg is "incorrect data check". While encoding the 12 Bytes with igzip, the return value of isal_inflate() is -6. However, I can decompress the 12 Bytes with zlib in python, and get the original 4 Bytes.  The python code is as below.
```
import zlib
def zlibDecompress(data):  
    zo = zlib.decompressobj() 
    return zo.decompress(data)
data_test = b'\x78\x01\x72\x75\x99\xe0\x02\x00\x00\x00\xff\xff'
decompData = zlibDecompress(data_test)
print(decompData)
print(len(decompData))

**Comment by cielavenir** [comment]
Clear out what data stream you are handling; raw-deflate/zlib/gzip. 0x7801727599e002000000ffff is a zlib stream.

**Comment by cielavenir** [comment]
> encoding the 12 Bytes with igzip, the return value of isal_inflate() is -6

provide the full snippet to reproduce it

**Comment by rhpvorderman** [comment]
I tried to reproduce it using the python-bindings, but it works fine:
```
>>> import zlib
>>> from isal import igzip_lib
>>> compressed = igzip_lib.compress(b"\x45\x44\x90\x44", level=1)
>>> compressed
b'su\x99\xe0\x02\x00'
>>> zlib.decompress(compressed, wbits=-15)
b'ED\x90D'
```
The problem is that the adler32 checksum at the end of the stream is incorrect: `0x0000ffff` is not equal to the correct checksum for the data, which is `0x348015e`. 
How did you get this data exactly. Using the python bindings I get the correct checksum as well:
```
>>> hex(zlib.adler32(b"\x45\x44\x90\x44"))
'0x348015e'
>>> from isal import isal_zlib
>>> hex(isal_zlib.adler32(b"\x45\x44\x90\x44"))
'0x348015e'
```

**Comment by BeeBreeze** [comment]
> I tried to reproduce it using the python-bindings, but it works fine:
> 
> ```
> >>> import zlib
> >>> from isal import igzip_lib
> >>> compressed = igzip_lib.compress(b"\x45\x44\x90\x44", level=1)
> >>> compressed
> b'su\x99\xe0\x02\x00'
> >>> zlib.decompress(compressed, wbits=-15)
> b'ED\x90D'
> ```
> 
> The problem is that the adler32 checksum at the end of the stream is incorrect: `0x0000ffff` is not equal to the correct checksum for the data, which is `0x348015e`. How did you get this data exactly. Using the python bindings I get the correct checksum as well:
> 
> ```
> >>> hex(zlib.adler32(b"\x45\x44\x90\x44"))
> '0x348015e'
> >>> from isal import isal_zlib
> >>> hex(isal_zlib.adler32(b"\x45\x44\x90\x44"))
> '0x348015e'
> ```

@rhpvorderman Thanks a lot for your help. With your information, we fix the bug. Our wrapper is in C code, and this problem appears in streaming compressing. As a zlib-compatible wrapper, we try to deal with different flush-type in deflate(z_stream, flush), since zlib support 7 different types of flush, while igzip has only 3. For example, 
```
int deflate(z_stream z_stream, in flush){
      ...
      switch(flush){
        case Z_NO_FLUSH:
              // init or reset isal struct, stored in z_stream.state(not used in zlib)
              ...
              // set configuration
              ...
             isal_zstream.flush = NO_FLUSH;
             isal_zstream.end_of_stream = 0;
             // igzip compress
             ...                                                                                                                          
      }
  }
```
Then, we find that the checksum is 0x0000ffff, and neither zlib nor igzip can decode the compressed data. To fix it, end_of_stream shoulde be 1, instead of 0.

**Comment by cielavenir** [comment]
ah yes, end_of_stream=1 is like setting Z_FINISH in zlib.
