### ISSUE TITLE
Thread safety documentation update?

### ISSUE THREAD

**Issue by thewacokid** [intel/isa-l#249]
Perhaps this is obvious to some, but would it be possible to add something into the documentation about which functions in ISA-L are thread-safe and which are not?  I believe all of the _base implementations are thread-safe at a glance but all of the optimized inlined assembly is not - though I'm happy to be corrected if that is not the case.

Thanks!

**Comment by gbtucker** [comment]
All isa-l functions are thread-safe.  I pushed an internal PR with the following changes to doc/functions.md

### Threading

All ISA-L library functions are single threaded but reentrant and thread-safe
making it easy for users to incorporate with any threading library. The igzip
command line utility has threaded compression but not built by default. To add
to an automake build do `$ make D="-DHAVE_THREADS"`.
