### ISSUE TITLE
Upcoming release v2.31

### ISSUE THREAD

**Issue by pablodelara** [intel/isa-l#258]
We are working towards the next release of ISA-L (v2.31), trending towards January 2024. 
We would appreciate if ARM and PowerPC developers/users can test the current code, to make sure the library is bug free for all supported architectures.
Many thanks!

**Comment by pablodelara** [comment]
Update: we are looking into releasing next week, so if there are any outstanding issues (especially on ARM/PowerPC architectures, as we have limited testing on these).

**Comment by rhpvorderman** [comment]
I tested the [latest commit](https://github.com/intel/isa-l/commit/455fdded4e2c1e658a74005d2cdc66ff1649b78d) with the python-isal test suite on x86_64 and aarch64 and all tests passed. This is great, as I won't be needing to include a patched version of 2.30 after this 2.31 release.

**Comment by pablodelara** [comment]
Thanks @rhpvorderman!

**Comment by pablodelara** [comment]
Hi all. We are targeting the v2.31 release before the end of the week. We are now in code freeze, unless something critical needs a fix. Any further testing is much appreciated @rhpvorderman @liuqinfei and @gerrith3. Thanks!

**Comment by rhpvorderman** [comment]
[python-isal tests pass](https://github.com/pycompression/python-isal/actions/runs/7555237332/). The tests succeed on all major operating systems on x86_64 as well as on emulated aarch64 (linux). This only covers the use cases in the python bindings, which is basically most of igzip_lib. The rest of ISA-L is not covered.

**Comment by pablodelara** [comment]
Many thanks for such quick response, @rhpvorderman. Much appreciated!

**Comment by liuqinfei** [comment]
> Hi all. We are targeting the v2.31 release before the end of the week. We are now in code freeze, unless something critical needs a fix. Any further testing is much appreciated @rhpvorderman @liuqinfei and @gerrith3. Thanks!

I have verified the latest software version on aarch64 servers with openEuler OS. All isa-l unit tests has passed.

**Comment by rhpvorderman** [comment]
I saw the release. Thank you for all the work you put in making ISA-L up to date again @pablodelara!

**Comment by pablodelara** [comment]
Thanks @rhpvorderman for your contributions as well! Closing this thread :)
