### ISSUE TITLE
Add isal_zlib_header_init

### ISSUE THREAD

**Issue by mxmlnkn** [intel/isa-l#262]
`isal_gzip_header`, `isal_gzip_header_init`, and `isal_read_gzip_header` exist for gzip header parsing but only `isal_zlib_header` and `isal_read_zlib_header` exist for zlib header parsing.

I think `isal_zlib_header_init` should be added for consistency.

**Comment by pablodelara** [comment]
Thanks for your suggestion. It makes sense to me to add it. I would say it wasn't added because there are non-zero values set in isal_gzip_header_init, where as all isal_zlib_header is set to 0.

**Comment by pablodelara** [comment]
Function implemented, thanks for the suggestion.
