### ISSUE TITLE
v2.31.0 tag not annotated

### ISSUE THREAD

**Issue by rhpvorderman** [intel/isa-l#273]
This leads git describe to ignore it (see: https://stackoverflow.com/a/4154518/16437839). 

As a consequence in the python isal repo:

```
$ git submodule 
+bd226375027899087bd48f3e59b910430615cc0a src/isal/isa-l (v2.30.0-126-gbd22637)
```
Even though it is at v2.31.0. 

I know this is a minor issue. On the other hand it is also easy to fix:

```
git checkout v2.31.0
git tag -af v2.31.0
# Type a message: ISA-L version 2.31.0  (or something)
git push origin v2.31.0
```

Since the tag points at the same commit this is not going to break anyone.

**Comment by pablodelara** [comment]
Thanks for raising this issue. Could you check now?

**Comment by rhpvorderman** [comment]
```
$ git submodule
 bd226375027899087bd48f3e59b910430615cc0a src/isal/isa-l (v2.31.0)
```
Yes, it works now! Thanks!
