### ISSUE TITLE
ARM OSX build fails

### ISSUE THREAD

**Issue by rhpvorderman** [intel/isa-l#276]
I ran into this. I found: https://github.com/intel/isa-l/pull/226 is supposed to fix this. 

```
  CPPAS    crc/aarch64/crc16_t10dif_pmull.lo
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/crc16_t10dif_pmull-8d2f3f.s:208:9: error: unknown AArch64 fixup kind!
        ldr q_fold_const, fold_constant
        ^
```

Just making this issue in order to track the problem. I have very little skin in the game. Currently osx-arm64 are advised to use rosetta when using bioinformatics pacakges, so it is not a problem that the dependency is not natively compiled. 

When it does natively compile again, I will make sure the conda-forge channel puts out a binary distribution.

**Comment by cielavenir** [comment]
master HEAD builds now, though it might segfault (due to using x18), avoiding in under review

**Comment by cielavenir** [comment]
@rhpvorderman This is now fully fixed.

**Comment by rhpvorderman** [comment]
Great. Looking forward to the next ISA-L release. Thanks for all that work @cielavenir !

**Comment by cielavenir** [comment]
oh @rozhukov please test if isa-l HEAD works as expected....

**Comment by cielavenir** [comment]
oh @rhpvorderman please test if isa-l HEAD works as expected....

**Comment by cielavenir** [comment]
well, passed. https://github.com/cielavenir/python-isal-py2/actions/runs/8464068215

**Comment by rhpvorderman** [comment]
Thanks!

**Comment by corneliusroemer** [comment]
Very cool! Looking forward to release!
