### ISSUE TITLE
Mention Julia language bindings

### ISSUE THREAD

**Issue by jakobnissen** [intel/isa-l#289]
The Julia package `isa_l_jll` wraps isa-l, this could be mentioned on the [language bindings Wiki page](https://github.com/intel/isa-l/wiki/Language-Bindings), e.g. with the following description:

* [Julia](https://julialang.org/)
  - [isa_l_jll](https://juliahub.com/ui/Packages/General/isa_l_jll) is a Julia wrapper around the `igzip` executable and the library `libisal`.

**Comment by pablodelara** [comment]
Hi @jakobnissen. Sure, interesting to see another language binding. Could it be updated to v2.31?

**Comment by jakobnissen** [comment]
I can try to update it, sure! There were some issues when attempting to build v2.30 on all the platforms Julia supports: https://github.com/JuliaPackaging/Yggdrasil/pull/6779

**Comment by jakobnissen** [comment]
Done, it is now updated to 2.31

**Comment by pablodelara** [comment]
Thanks, issue #276 is fixed, will fix #283 soon.

**Comment by pablodelara** [comment]
Actually, is this binding implementing wrappers for all functions, or only compression (igzip)?

**Comment by jakobnissen** [comment]
All functions - it also wraps `libisal`.
