### ISSUE TITLE
Update Generic C implementation

### ISSUE THREAD

**Issue by encode84** [intel/isa-l#298]
Hello,
Please update the Generic C implementation to match the ASM code. Currently it is vastly different from X86-64 ASM. In particular with ASM version you use speculative hash computation (hash/hash2) to output either match or literal + match

**Comment by pablodelara** [comment]
Hi @encode84. Sorry for the delay on the response. The generic C implementation is not meant to be fully optimized for any architecture, so we won't be able to help here.
