### ISSUE TITLE
Erasure code support for PowerPC

### ISSUE THREAD

**Issue by daxtens** [intel/isa-l#7]
Hi!

I've been working on accelerating erasure codes on 64-bit PowerPC systems. 

I've found that ISA-L has significantly lower overhead than jerasure/gf-complete due to ISA-L's performance-orientated design. As such, I've written a bunch of PowerPC assembler erasure-code routines for ISA-L. They are largely self-contained and require little change to the generic C code. There's no impact to performance or functionality on x86.

If I were to submit these as a pull-request, would you be open to accepting them? 

Just to be clear, I'm not asking you to accept the code sight unseen, I'm just asking for an "in principle" answer on whether you'd be OK with non-x86 code or if you'd reject it out-of-hand.

Thanks in advance!

**Comment by JonathanStern** [comment]
Daniel,
We haven't had a request of this nature before, so we need a bit of time to figure out exactly what our policy should be. In principle, we're not against new implementations, provided they are fully API-compatible with the existing implementations. Can you share a bit of detail about the changes required to the generic C code? 

Thank you,
Jonathan Stern
ISA-L Applications Engineer

**Comment by daxtens** [comment]
Hi Jonathan,

Thanks for your response.

API compatibility is critical to what I'm trying to achieve, so I'm fully committed to keeping it. I don't want to change or remove any function signatures, I only want to add `_altivec` versions of the existing functions (e.g. `ec_encode_data_altivec`).

With regards to the generic C code, there's only one change I'd like to upstream. The vector unit on modern little-endian Power chips reads in the gf tables backwards, so I have changed the C code in `gf_vect_mul_init` to generate them backwards on Power.

I haven't cleaned up the code for upstreaming yet, but I noticed that there's already an `#ifdef` in that function for generating the tables differently for 64 vs 32 bit, so I was planning to add another test for Power and put that code there.

I have also changed places in C where the gf tables are accessed to reverse the indexing. It would be pretty straight-forward to add a macro to paper over this difference, for example:

```
#ifdef __powerpc__
#define GF_ENTRY(x) (15-(x))
#else
#define GF_ENTRY(x) (x)
#endif
```

Then call-sites would look like:

```
s ^= gf_mul(src[j][i], v[j * 32 + GF_ENTRY(1)]);
```

I'm happy to implement this in another way if you'd prefer, or if this is a deal-breaker I can leave the C code unchanged and reverse the tables in Power-specific code at the cost of a small speed penalty on Power.

Hopefully that answers your questions. Let me know if there's any more info you'd like.

Regards,
Daniel

**Comment by daxtens** [comment]
Hi Jonathan,

Just checking in on this. I appreciate that these processes take time, so I'm not trying to rush you, I was just wondering if you have an estimated timeline for when you might have an answer.

If there's anything I can do to help, please let me know.

Regards,
Daniel

**Comment by JonathanStern** [comment]
Daniel,

We're in the middle of the process now, and figure we'll have a firm answer no later than end of November.

Hope that helps! We'll update you as soon as we can.

-- Jonathan Stern

**Comment by JonathanStern** [comment]
Hey Daniel, 

I'm pleased to let you know that we're able to accept patches for other architectures. We'll want to sync up  on some implementation details around the generic C code -- I'd like to put you in touch with the ISA-L tech lead directly, if possible. 

Thanks!

-- Jonathan Stern

**Comment by daxtens** [comment]
Hi Jonathan,

That's excellent news - thank you!

I'm happy to sync up, either here or you can email me at dja at (my last name) dot net.

Regards,
Daniel

**Comment by ayappanec** [comment]
Hi Guys, any update on this ?

**Comment by gbtucker** [comment]
We pushed all the multi-arch changes with the updates for 2.18 already.  I expected to see Daniel rebase his fixes by now.  I'll ping him to make sure he has seen it.

**Comment by daxtens** [comment]
Ah, sorry I missed it. I'll get someone on to that very soon.

**Comment by smatzek** [comment]
@gbtucker To be transparent, Daniel changed employers.  We are still in the process of getting developers together to pick up the pieces, understand the remaining work items, and carry the EC optimizations for ppc64 forward into ISAL.  The dev team is currently working through rebase issues with the master branch.  @daxtens the fixes Greg is referring to- do you have remaining fixes in your fork that need to go back via PR?

**Comment by gbtucker** [comment]
Thanks for the update.

**Comment by jyvet** [comment]
Hi, do you know by any chance if your contribution will be available soon? Can I help to get these patches merged?

**Comment by guymguym** [comment]
Hi. Is this on someone's queue?

**Comment by gbtucker** [comment]
We integrated powerpc EC support with 180c74a.  Perhaps I should close the issue.

**Comment by guymguym** [comment]
Thanks @gbtucker :) So seems like you can close this issue.

BTW do you know what would it take to support arch=s390x (Linux on IBM Z)?

**Comment by gbtucker** [comment]
I'm not sure what it would take to make specialized s390x versions but it should build and run now using the base functions in C.

**Comment by daxtens** [comment]
Yes, this should be closed now.

Guy, if you are interested in optimised s390x versions I can reach out to
some people in IBM and see what their position is. Let me know.

**Comment by guymguym** [comment]
Hey @daxtens yes thank you it would be most appreciated (CC @liranmauda).

**Comment by daxtens** [comment]
No worries. Would you mind shooting me an email at daniel.axtens1@ibm.com
and we can go from there? I should warn you I work in the Power division
not the System Z division, so it might take me awhile to find the right
person!
