### ISSUE TITLE
igzip: A small question about igzip

### ISSUE THREAD

**Issue by zhiyuan-zhu** [intel/isa-l#73]
@gbtucker 
There is a function in igzip/huffman.h, named: static inline uint32_t compute_hash(uint32_t data)
When enable and disable the macro: __SSE4_2__, the result of hash value is different.
So, can I just replace this function with any crc32 algorithm? thanks.

182 static inline uint32_t compute_hash(uint32_t data)
183 {
184 #ifdef __SSE4_2__
185
186         return _mm_crc32_u32(0, data);
187
188 #else
189         uint64_t hash;
190         /* Use multiplication to create a hash, 0xBDD06057 is a prime number */
191         hash = data;
192         hash *= 0xB2D06057;
193         hash >>= 16;
194         hash *= 0xB2D06057;
195         hash >>= 16;
196
197         return hash;
198
199 #endif /* __SSE4_2__ */
200 }

**Comment by gbtucker** [comment]
We do use a different hash in different situations.  You could implement a different hash but it must be consistent such as when initializing a dictionary.

**Comment by zhiyuan-zhu** [comment]
@gbtucker thanks for your fast and useful reply, closed this issue.
