### ISSUE TITLE
error: '_aligned_malloc' was not declared in this scope

### ISSUE THREAD

**Issue by bolunfeng** [intel/isa-l#80]
I used the MinGW tool on the Windows 7 platform to compile libisal_crypto.a and libisal.a one by one (gcc compiles each .o file, then ar *.o), but when the link is used, it returns a mistake.

D:/software/gt_compress/lib/win/gcc/debug/intel/isa-l_crypto/include/isa-l_crypto/types.h:52:101: error: '_aligned_malloc' was not declared in this scope
 #   define posix_memalign(p, algn, len) (NULL == (*((char**)(p)) = (void*) _aligned_malloc(len, algn)))

**Comment by gbtucker** [comment]
Malloc isn't called in the library but many of the unit tests do and this translation is used as a convenience to get a common aligned allocate function with windows and posix.  Can you confirm this is in the library link step and not in the unit test build `make checks`?  It seems odd that an unused define can cause an error.  If really possible we can move it to the test helper include test.h that is never included by the library files.  If the error is in unit test build perhaps we just missed a system include.
