### ISSUE TITLE
Document mistake

### ISSUE THREAD

**Issue by g199209** [intel/isa-l#86]
In ["ISA-L v2.19 Performance Report"](https://01.org/sites/default/files/documentation/intel_isa-l_2.19_performance_report_0.pdf) which is listed in Wiki Documentation page. 

p18:
![](https://gmf.shengnengjin.cn/WeWork%20Helper20190911112116.png)

CPU information in the table is wrong, which should be Atom C3985.

**Comment by alantu02** [comment]
Thanks @g199209.
The corrections have been made and a new document will be uploaded.

**Comment by gbtucker** [comment]
Thanks for the catch.  Update has been uploaded.
