### ISSUE TITLE
can not visit mail list

### ISSUE THREAD

**Issue by wangxiyuan** [intel/isa-l#97]
I want to subscribe mail list following the guide. But the url can be visited. What's the correct url now?
https://lists.01.org/mailman/listinfo/isal

**Comment by gbtucker** [comment]
Sorry about that.  It looks like the management of the lists has moved to https://lists.01.org/hyperkitty/list/isal@lists.01.org/.  I'll see about updating links in the docs.

**Comment by wangxiyuan** [comment]
@gbtucker , thank you. The new link works for me.

**Comment by gbtucker** [comment]
Updated in readme.  Thanks for the catch.
